[workspace]
members = [
    "undohistory",
    "mars",
    "droptest",
    "scoped",
    "imtest",
    "sharingtest",
    "polymorphic_variance",
]

[workspace.package]
authors = ["m. interrupt"]
edition = "2021"
description = "A bunch of libraries"
