[package]
name = "undohistory"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
im = { version = "15.1.0", features = ["serde"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
